// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD577tZ7E74HIz_n_qWZHvzvvzdRzsO8Uc',
    appId: '1:1043281507525:web:eeb5683b99dfc1a60c2cac',
    messagingSenderId: '1043281507525',
    projectId: 'flutter-firebase-chat-ff3d1',
    authDomain: 'flutter-firebase-chat-ff3d1.firebaseapp.com',
    storageBucket: 'flutter-firebase-chat-ff3d1.appspot.com',
    measurementId: 'G-HTM7WN3MRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDabhrXI5yEICEmg765oNyIo9SPmFhTMb4',
    appId: '1:1043281507525:android:5fda96c2497576680c2cac',
    messagingSenderId: '1043281507525',
    projectId: 'flutter-firebase-chat-ff3d1',
    storageBucket: 'flutter-firebase-chat-ff3d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvdpEx_GbqAMtN4BHzfuPlJLOL_IqUZUI',
    appId: '1:1043281507525:ios:55678dbcd7ca729d0c2cac',
    messagingSenderId: '1043281507525',
    projectId: 'flutter-firebase-chat-ff3d1',
    storageBucket: 'flutter-firebase-chat-ff3d1.appspot.com',
    iosClientId: '1043281507525-1fi3uo2co3kip33ubmip6km9us5ennep.apps.googleusercontent.com',
    iosBundleId: 'com.dsilvera.flutterFirebase',
  );
}
